### ISSUE TITLE
Описать API  для Rabbit

### ISSUE THREAD

**Issue by Teastan0** [csu-automl/starter#4]

**Comment by batarelkin** [comment]
Замечания:
* data-worker
  в описание добавить информацию о том, что это именно worker очередь (Work queues)
  убрать key, добавить id в тело сообщения
* data-worker-status
  в описание добавить информацию о том, что это pubsub очередь (Publish/Subscribe)
  убираем key и status в тело.
  статусов будет 3: starter, completed, failed
  для каждого статуса описать свой формат сообщения

**Comment by jen6666** [comment]
`{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Rabbit API"
  },
  "schemes": [
    "http"
  ],
  "paths": {
    "/data-worker": {
      "post": {
        "summary": "Dataset's work queue",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body message",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BodyMesgWork"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/data-worker-status/started": {
      "post": {
        "summary": "Dataset status's pubsub queue",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body message",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BodyMesgPubsubStarted"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/data-worker-status/completed": {
      "post": {
        "summary": "Dataset status's pubsub queue",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body message",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BodyMesgPubsubCompleted"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/data-worker-status/failed": {
      "post": {
        "summary": "Dataset status's pubsub queue",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body message",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BodyMesgPubsubFailed"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "Column": {
      "type": "object",
      "required": [
        "index",
        "type"
      ],
      "properties": {
        "index": {
          "type": "integer",
          "format": "int32"
        },
        "type": {
          "type": "string",
          "enum": [
            "number",
            "categorical"
          ]
        },
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        }
      }
    },
    "BodyMesgWork": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "columns": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Column"
          }
        }
      }
    },
    "BodyMesgPubsubStarted": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "example": "started"
        }
      }
    },
    "BodyMesgPubsubCompleted": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "example": "completed"
        },
        "columns": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Column"
          }
        }
      }
    },
    "BodyMesgPubsubFailed": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "example": "failed"
        },
        "error": {
          "type": "string"
        }
      }
    }
  }
}`
